version: 0.2

env:
  variables:
    AWS_REGION: us-east-2
    REPOSITORY_URI: 060795918949.dkr.ecr.us-east-2.amazonaws.com/fun-with-the-bible
    IMAGE_TAG: latest
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: 3.10
      nodejs: 18
    commands:
      - echo Installing Python dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - echo Installing Node.js dependencies...
      - npm install
      - npm install -g @tailwindcss/cli
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Building Tailwind CSS...
      - npx tailwindcss -i ./static/css/styles.css -o ./static/css/app.css
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed on `date`
cache:
  paths:
    - '/root/.cache/pip'
    - 'node_modules/**/*'
